### ISSUE TITLE
Implement new API spec on backend

### ISSUE THREAD

**Issue by bgianfo** [bgianfo/distributed-systems#13]
Sam was awesome enough to write a formal API spec, it fixes some uglies that I had in my original implementation. 

 Check it: https://github.com/bgianfo/distributed-systems/raw/master/doc/API.txt

Needs to be implemented ASAP.

**Comment by srm2997** [comment]
I included "Error Code?" for invalid stuff frequently.
Do we want to make an error code system? ex:
1 = username taken
2 = invalid pass
etc
Could also have it return a string of what the message was, or should we just have it return 'err' and let the client guess which it was?

**Comment by bgianfo** [comment]
For the login example I don't think we should tell the client why login failed.

I think that's general bad practice to report a invalid password. It's possible someone could just try random user names until they get a bad pass and then just brute force the password.

But for any of the other call's I think it makes sense to have an error code system.

**Comment by srm2997** [comment]
Agreed, really meant invalid user/pass combo. Error codes are fine with me.  I'd say they can just be made up on the spot, but note them in the API document.
