### ISSUE TITLE
Load Balancer down connection issues

### ISSUE THREAD

**Issue by StickyDL** [bgianfo/distributed-systems#14]
Whenever a load balancer is down, at least on the Android client, the connection reliability is random

**Comment by bgianfo** [comment]
I set us up for a service, which monitor's the load balancers. 
  If either of the load balancers is down, the service automatically removes it from our DNS entry. 
  This will stop the problem of the clients being directed to a non existent load balancer. 

  We can see how this work's, I'll leave this issue open for now...

**Comment by bgianfo** [comment]
This fix above seems to have fixed these problems.
